### ISSUE TITLE
Missing configure_requires dependency ExtUtils::MakeMaker::META_MERGE::GitHub

### ISSUE THREAD

**Issue by eserte** [mrdvt92/perl-Power-Outlet#1]
Probably the same issue as https://github.com/mrdvt92/perl-Excel-Writer-XLSX-Simple-Tabs/issues/1

**Comment by mrdvt92** [comment]
Used the copy/paste example of ExtUtils::MakeMaker::META_MERGE::GitHub so, that it's not a configure_requires dependency.

But, I could have added the CONFIGURE_REQUIRES to the WriteMakefile like...

```
  use ExtUtils::MakeMaker;
  use ExtUtils::MakeMaker::META_MERGE::GitHub;
  my $mm = ExtUtils::MakeMaker::META_MERGE::GitHub->new(owner=>"myowner", repo=>"myrepo");
  WriteMakefile(
                CONFIGURE_REQUIRES => {'ExtUtils::MakeMaker::META_MERGE::GitHub' => 0},
                $mm->META_MERGE,
                ...
               );
```

Fixed in version 0.45
